cmd =	default-param \
	hash-paren id-clear id-rewrite psynth uparam sexp \
	scsyndef-stat scsyndef-to-dot scsyndef-to-fs scsyndef-to-hs \
	scsynth-reset scsynth-status \
	setup

include ~/sw/hsc3/mk/cmd.mk
